### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by DavidMStraub** [DavidMStraub/gramps-webapp#16]
Need to investigate whether the app can run with Gramps on Windows.

**Comment by tester0077** [comment]
If I can be of any help, please let me know.

**Comment by vnl** [comment]
@DavidMStraub ~~How may I help? I can test this out. I will install the repo using the instructions. The read me says, deployment instructions to follow.~~
I will let you know how it works.

**Comment by vnl** [comment]
I get the following running the command
```
C:\dev>python3 -m gramps_webapp app -O 'Sample' --no-auth run
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\vivia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\gramps_webapp\__main__.py", line 5, in <module>
    from .api import create_app, get_db
  File "C:\Users\vivia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\gramps_webapp\api.py", line 42, in <module>
    from .db import Db
  File "C:\Users\vivia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\gramps_webapp\db.py", line 6, in <module>
    from gramps.cli.clidbman import CLIDbManager
ModuleNotFoundError: No module named 'gramps'
```

**Comment by DavidMStraub** [comment]
Thanks! Do you have Gramps Desktop installed? Which installation method did you use? I suspect the Windows version comes bundled with its own Python environment?

**Comment by vnl** [comment]
I do have Gramps installed. GrampsAIO64-5.1.2-1. I think it does have its own. 
![image](https://user-images.githubusercontent.com/1355466/89735898-8c5de980-da5d-11ea-9a2f-aa5f8699dbf1.png)
